FrontendPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('shop/', include('product.urls')),
    path('contacts/', include('contacts.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('news/', include('news.urls')),
    path('', include('mainFront.urls')),
    path('collection/', include('collection.urls')),
    path('order/', include('order.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.Collections.as_view(), name='collection'),
    path('buy_collection', views.buy_collection, name='buy_collection'),
    path('<slug:slug>/<str:gender>/', views.SliderCollection.as_view(), name='slider_collection'),
    path('make_col_order/', views.make_col_order, name='make_col_order'),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.MyNews.as_view(), name='news'),
    path('<slug:slug>/', views.load_news, name='load_news'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('<slug:slug>/', views.CategoriesItems.as_view(), name='categories'),
    path('<str:gender>/<slug:cat_slug>/<slug:prod_slug>/', views.product_detail, name='product_detail'),
]

collection/models.py
from django.db import models
from django.db.models import BooleanField

from order.const import DELIVERY_REGIONS


class Collection(models.Model):
    collection_name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=40, unique=True, db_index=True, verbose_name='URL')
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='collection_img/', verbose_name='Изображение коллекции')
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return self.collection_name

collection/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .local_url_generator import local_url_generator
from .models import Collection
from product.models import Product, ProductSize, ProductColor
from order.models import CollectionOrder, ProductInCollectionOrder, Status
from django.views.generic import ListView
from order.views import get_session_key
from order.tg import telegram_bot_send_col_order_text
from order.mail import send_email
import os

host = os.environ.get('HOSTNAME')


class Collections(ListView):
    paginate_by = 9
    model = Collection
    template_name = 'collection/collection.html'
    context_object_name = 'collections'

    def get_queryset(self, **kwargs):
        return Collection.objects.filter(is_active=True)


class SliderCollection(ListView):
    model = Product
    template_name = 'collection/slider_collection.html'
    context_object_name = 'parsed_collection'

    def get_queryset(self, **kwargs):
        global slug
        global gender
        slug = self.kwargs['slug']
        gender = self.kwargs['gender']
        return Product.objects.filter(collection__slug=slug, gender=gender, in_stock=True).select_related('category')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        col = Collection.objects.get(slug=slug)
        context['col_name'] = col.collection_name

        sizes = ProductSize.objects.filter(product__collection__slug=slug, product__gender=gender)
        colors = ProductColor.objects.filter(product__collection__slug=slug, product__gender=gender)
        context['sizes'] = sizes
        context['colors'] = colors
        context['gender'] = gender
        return context


def buy_collection(request):
    if request.method == 'POST':
        data = request.POST
        url_from = data.get('url_from')
        order_price = int(data.get('discount-price'))
        discount = data.get('discount-percent')
        ids = data.get('discount-ids')
        gender = data.get('gender')
        sizes = data.getlist('chosen-size')
        colors = data.getlist('chosen-color')
        print('sizes: ', sizes)
        print('ids: ', ids)
        item_dicts = []
        sizes_list = list()
        colors_list = list()
        split_ids = ids.split(',')
        first_id = int(split_ids[0])
        collection_name = Product.objects.get(id=first_id).collection.collection_name
        order_list = list()
        print('ids:', ids.split(','))
        for item in ids.split(','):
            n_dict = dict()
            order_string = '-'
            qs = Product.objects.filter(id=int(item)).select_related('category')

            n_dict['id'] = int(item)
            order_string += item + '-'
            for prod in qs:
                n_dict['category'] = prod.category.category
                n_dict['category_slug'] = prod.category.slug
                n_dict['title'] = prod.title
                n_dict['slug'] = prod.slug
                n_dict['image'] = prod.main_image.url
                n_dict['item_price'] = prod.price



            for size in sizes:
                parsed = size.split('=')
                if parsed[0] == item:
                    if parsed[1]:
                        n_dict['size'] = parsed[1]
                        break
                    else:
                        n_dict['size'] = 'UniSize'
                        break

            for color in colors:
                parsed = color.split('=')
                if parsed[0] == item:
                    if parsed[1]:
                        n_dict['color'] = parsed[1]
                        break
                    else:
                        n_dict['color'] = '***'
                        break
            item_dicts.append(n_dict)
            order_list.append(order_string)

        for i in ids.split(','):
            for size in sizes:
                parsed = size.split('=')
                if parsed[0] == i:
                    if parsed[1]:
                        sizes_list.append(parsed[1])
                    else:
                        sizes_list.append('UniSize')

        for i in ids.split(','):
            for color in colors:
                parsed = color.split('=')
                if parsed[0] == i:
                    if parsed[1]:
                        colors_list.append(parsed[1])
                    else:
                        colors_list.append('***')

        order_sizes = ','.join(sizes_list)
        order_colors = ','.join(colors_list)

        return render(request, 'collection/buy_collection.html', {'set': item_dicts,
                                                                  'collection_name': collection_name,
                                                                  'order_price': order_price,
                                                                  'discount': discount,
                                                                  'gender': gender,
                                                                  'order_list': order_list,
                                                                  'order_sizes': order_sizes,
                                                                  'order_colors': order_colors,
                                                                  'ids': ids,
                                                                  'url_from': url_from,
                                                                  })
    else:
        return render(request, 'mainFront/page404.html')


def make_col_order(request):
    data = request.POST
    if request.method == 'POST':
        user = get_session_key(request)
        customer_name = data.get('customer_name')
        customer_email = data.get('customer_email')
        customer_phone = data.get('customer_phone')
        order_price = int(data.get('order-price'))
        discount_percent = data.get('discount-percent')
        delivery_region = data.get('delivery_region')
        delivery_district = data.get('delivery_district')
        delivery_city = data.get('delivery_city')
        nova_poshta_departament = data.get('nova_poshta')
        comment = data.get('comment')

        col_order = CollectionOrder.objects.create(
            user=user,
            order_price=order_price,
            discount_percent=discount_percent,
            customer_name=customer_name,
            customer_email=customer_email,
            customer_phone=customer_phone,
            delivery_region=delivery_region,
            delivery_district=delivery_district,
            delivery_city=delivery_city,
            nova_poshta_departament=nova_poshta_departament,
            comment=comment,
            status=Status.objects.get(id=1)
        )

        ids = data.get('ids').split(',')
        sizes = data.get('sizes').split(',')
        colors = data.get('colors').split(',')

        for i in range(len(ids)):
            product = get_object_or_404(Product, id=int(ids[i]))

            ProductInCollectionOrder.objects.create(col_order=col_order,
                                                    product=product,
                                                    size=sizes[i],
                                                    color=colors[i],
                                                    price_per_item=product.price)

        url_from = data.get('url_from')
        print(telegram_bot_send_col_order_text(order=col_order,
                                         products=ProductInCollectionOrder.objects.filter
                                         (col_order_id=col_order.id).select_related('product')))
        send_email(col_order, '{}/order/completed_col_detail/{}'.format(request.get_host(), col_order.id))

        return redirect(
            '{}order/completed_col_detail/{}'.format(local_url_generator(url=data.get('url_from')), col_order.id))

collection/templates/collection/buy_collection.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Collections{%endblock%}
{% load i18n %}
{% block content %}


        <h1 style="text-align: center; margin-top: 100px;  font-size: 26px;">{% trans 'ORDER AS COLLECTION' %} </h1>
<div class="wrap-wrap-wrapper">
<div class="wrap-wrapper">
    <div class="col-buy-wrapper">
        <h4>{{collection_name}}</h4>
        {% for dict in set %}
            <div class="item-card">
                <div class="col-buy-image">
                    <img src="{{dict.image}}">
                </div>
                <div class="col-buy-details-wrapper">
                    <div class="col-buy-details">
                        <div>{% trans 'Title' %}: <span style="color: #dd5145; font-weight: 500;">{{dict.title}}</span></div>
                        <div>{% trans 'Category' %}: <span style="color: #dd5145; font-weight: 500;">{{dict.category}}</span></div>
                        <div>{% trans 'Price' %}: <span style="color: #dd5145; font-weight: 500;">{{dict.item_price}}</span></div>
                        <div>{% trans 'Size' %}: <span style="color: #dd5145; font-weight: 500;">{{dict.size}}</span></div>
                        <div>{% trans 'Color' %}: <span style="color: #dd5145; font-weight: 500;">{{dict.color}}</span></div>
                        <a class="details-link" href="{% url 'product:product_detail' gender dict.category_slug dict.slug %}">{% trans 'Details' %}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="col-buy-form-wrapper">
        <div class="col-buy-form">

            <form id="coll-buy-form" method="post" action="{% url 'collection:make_col_order' %}"> {% csrf_token %}
                <div class="form1">
                        <h4 style="margin-bottom: 20px">{% trans 'Order form' %}</h4>

                        <input class="form1-group" name="customer_name" type="text" placeholder="{% trans 'name' %}" required><br>
                        <input class="form1-group" name="customer_email" type="email" placeholder="emailExample@gmail.com" required><br>
                        <input class="form1-group" data-tel-input name="customer_phone" maxlength="19" type="tel" placeholder="{% trans 'phone' %}" required><br>

                        <div class="discount-info">
                            <span class="discount-field">{% trans 'Your discount' %}: 
                                <span style="color: #dd5145">{{ discount }}</span></span><br>
                            <span class="discount-field">{% trans 'Order price' %}: 
                                <span style="color: #dd5145">{{order_price}}</span></span><br><br>
                        </div>


                        <label style="font-size: 18px; ">{% trans 'Delivery info' %}</label><br><br>
                        <select name="delivery_region" class="delivery_region form1-group">
                            <option value="VINNYTSKA OBL">Вiнницька область</option>
                            <option value="VOLYNSKA OBL">Волинська область</option>
                            <option value="DNIPROPETROVSKA OBL">Днiпропетровська область</option>
                            <option value="DONETSKA OBL">Донецька область</option>
                            <option value="JYTOMYRSKA OBL">Житомирська область</option>
                            <option value="ZAKARPATSKA OBL">Закарпатська область</option>
                            <option value="ZAPORIJSKA OBL">Запорiжська область</option>
                            <option value="IVANO FRANKIVSKA OBL">Iвано-Франкiвська область</option>
                            <option value="KYIVSKA OBL">Київська область</option>
                            <option value="KIROVOGRADSKA OBL">Кiровоградська область</option>
                            <option value="LUHANSKA OBL">Луганська область</option>
                            <option value="LVIVSKA OBL">Львiвська область</option>
                            <option value="MYKOLAIVSKA OBL">Миколаївська область</option>
                            <option value="ODESKA OBL">Одеська область</option>
                            <option value="POLTAVSKA OBL">Полтавська область</option>
                            <option value="RIVNENSKA OBL">Рiвненська область</option>
                            <option value="SUMSKA OBL">Сумська область</option>
                            <option value="TERBOPILSKA OBL">Тернопiльська область</option>
                            <option value="KHARKIVSKA OBL">Харкiвська область</option>
                            <option value="KHERSONSKA OBL">Херсонська область</option>
                            <option value="KHMELNYTSKA OBL">Хмельницька область</option>
                            <option value="CHERKASKA OBL">Черкаська область</option>
                            <option value="CHERNIHIVSKA OBL">Чернiгiвська область</option>
                            <option value="CHERNIVETSKA OBL">Чернiвецька область</option>
                        </select><br>

                        <input class="form1-group" name="delivery_district" type="text" placeholder="{% trans 'district (optional)' %}"><br>
                        <input class="form1-group" name="delivery_city" type="text" placeholder="{% trans 'city or town' %}" required><br>
                        <input class="form1-group" name="nova_poshta" type="number" placeholder="{% trans 'nova poshta №' %}" min="1" required><br>
                        <input class="form1-group" name="comment" type="textarea" size="60" placeholder="{% trans 'comment (optional)' %}"><br>
                        <div class="checkbox">
                            <input class="checkbox__input" type="checkbox" name="agreement" required id="agreement">
                            <label class="checkbox__label" for="agreement">{% trans 'I agree with data processing rules' %}</label>
                        </div>
                        <input type="hidden" name="url_from" value="{{request.path}}">
                        <input  type="hidden" name="order-price" value="{{order_price}}">
                        <input  type="hidden" name="discount-percent" value="{{discount}}">
                        <input  type="hidden" name="set" value="{{order_list}}">
                        <input  type="hidden" name="ids" value="{{ids}}">
                        <input  type="hidden" name="sizes" value="{{order_sizes}}">
                        <input  type="hidden" name="colors" value="{{order_colors}}">
                        <button  type="submit" class="form1-submit_button" >{% trans 'Checkout' %}</button>
                </div>

            </form>
        </div>
    </div>

</div>
<a class="cancel-a" href="{{url_from}}"><div class="cancel">{% trans 'Cancel' %}</div></a>
</div>
<script src="{% static 'mainFront/js/inputMask.js' %}"></script>

{% endblock %}


collection/templates/collection/slider_collection.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Collections{%endblock%}
{% load i18n %}
{% block content %}
{% if parsed_collection %}
<h1 style="text-align: center; margin-top: 100px;  font-size: 26px;"> {{ col_name }} </h1>
<form method="post" action="{% url 'collection:buy_collection' %}" style="padding: 10px;"> {% csrf_token %}
<div class="col-wrapper">
    <div class="col-top-wrapper">
        <div class="top-slider">


            {% for item in parsed_collection %}
                {% if item.category.slug == 'hats' or item.category.slug == 'jewellery' %}


                    <div class="col-section-content">

                        <div class="col-image">
                            <div class="radio-wrap">
                                <div class="radio">
                                    <input class="top-slider-chek js" type="checkbox" id="{{item.id}}" name="{{item.price}}">

                                    <label class="top-label" for="{{item.id}}"></label>
                                </div>
                            </div>
                            <img src="{{item.main_image.url}}" alt="QWE">
                        </div>

                        <div class="hidden-form">
                            <div class="form-item-desc">
                                <span>{% trans 'Title' %}: {{item.title}}</span><br>
                                <span>{% trans 'Price' %}: {{item.price}} {% trans 'UAH' %}</span><br>
                                <span>{% trans 'Category' %}: {{item.category.category}}</span><br>
                                <a href="{% url 'product:product_detail' gender item.category.slug item.slug %}">{% trans 'View details' %}</a>
                            </div>
                        <div class="select-hid-wrapper">
                            <div class="select select-size">
                                <div class="select__header select__header_size">
                                    <span class="select__current_size">{% trans 'Size' %}</span>
                                </div>
                                <input type="hidden" class="chosen-size {{item.id}}" name="chosen-size" value="{{item.id}}=">
                                <div class="select__body select__body_size">
                                        {% for s in sizes %}
                                            {% if s.product_id == item.id %}
                                                <div class="select__item select__item_size">{{s.size}}</div>
                                            {% endif %}
                                        {% endfor %}

                                </div>
                            </div>

                            <div class="select color-select">
                                <div class="select__header select__header_color">
                                    <span class="select__current select__current_color">{% trans 'Color' %}</span>
                                </div>
                                <input type="hidden" class="chosen-color {{item.id}}" name="chosen-color" value="{{item.id}}=">
                                <div class="select__body select__body_color">

                                        {% for color in colors %}
                                            {% if color.product_id == item.id %}
                                                <div class="select__item select__item_color">{{color.color_name}}</div>
                                            {% endif %}
                                        {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>

    <div class="col-mid-wrapper">
        <div class="top-slider">


            {% for item in parsed_collection %}
                {% if item.category.slug == 'tshirts' or item.category.slug == 'sweatshirts' or item.category.slug == 'shirts' or item.category.slug == 'outerwear' or item.category.slug == 'underwear' or item.category.slug == 'accessories' %}
                    <div class="col-section-content">

                        <div class="col-image">
                            <div class="radio-wrap">
                                <div class="radio">
                                    <input class="mid-slider-chek js" type="checkbox" id="{{item.id}}" name="{{item.price}}">
                                    <label class="mid-label" for="{{item.id}}"></label>
                                </div>
                            </div>
                            <img src="{{item.main_image.url}}" alt="QWE">
                        </div>

                        <div class="hidden-form">
                            <div class="form-item-desc">
                                <span>{% trans 'Title' %}: {{item.title}}</span><br>
                                <span>{% trans 'Price' %}: {{item.price}} {% trans 'UAH' %}</span><br>
                                <span>{% trans 'Category' %}: {{item.category.category}}</span><br>
                                <a href="{% url 'product:product_detail' gender item.category.slug item.slug %}">{% trans 'View details' %}</a>
                            </div>
                             <div class="select-hid-wrapper">
                            <div class="select select-size">
                                <div class="select__header select__header_size">
                                    <span class="select__current_size">{% trans 'Size' %}</span>
                                </div>
                                <input type="hidden" class="chosen-size {{item.id}}" name="chosen-size" value="{{item.id}}=">
                                <div class="select__body select__body_size">
                                    {% for s in sizes %}
                                        {% if s.product_id == item.id %}
                                            <div class="select__item select__item_size">{{s.size}}</div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="select color-select">
                                <div class="select__header select__header_color">
                                    <span class="select__current select__current_color">{% trans 'Color' %}</span>
                                </div>
                                <input type="hidden" class="chosen-color {{item.id}}" name="chosen-color" value="{{item.id}}=">
                                <div class="select__body select__body_color">
                                        {% for color in colors %}
                                            {% if color.product_id == item.id %}
                                                <div class="select__item select__item_color">{{color.color_name}}</div>
                                            {% endif %}
                                        {% endfor %}
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="col-bot-wrapper">
        <div class="top-slider">


            {% for item in parsed_collection %}
                {% if item.category.slug == 'shorts' or item.category.slug == 'trousers' or item.category.slug == 'socks' or item.category.slug == 'footwear'  %}
                    <div class="col-section-content">

                        <div class="col-image">
                            <div class="radio-wrap">
                                <div class="radio">
                                    <input class="bot-slider-chek js"  type="checkbox" id="{{item.id}}" name="{{item.price}}">

                                    <label class="bot-label" for="{{item.id}}"></label>
                                </div>
                            </div>
                            <img src="{{item.main_image.url}}" alt="QWE">
                        </div>

                        <div class="hidden-form">
                            <div class="form-item-desc">
                                <span>{% trans 'Title' %}: {{item.title}}</span><br>
                                <span>{% trans 'Price' %}: {{item.price}} {% trans 'UAH' %}</span><br>
                                <span>{% trans 'Category' %}: {{item.category.category}}</span><br>
                                <a href="{% url 'product:product_detail' gender item.category.slug item.slug %}">{% trans 'View details' %}</a>
                            </div>
                            <div class="select-hid-wrapper">
                            <div class="select select-size">
                                <div class="select__header select__header_size">

                                    <span class="select__current_size" data-item_id="{{item.id}}">{% trans 'Size' %}
                                        <input type="hidden" class="for-size-id" value="{{item.id}}">
                                    </span>
                                </div>
                                <input type="hidden" class="chosen-size {{item.id}}" name="chosen-size" value="{{item.id}}=">
                                <div class="select__body select__body_size" >
                                    {% for s in sizes %}
                                            {% if s.product_id == item.id %}
                                                <div class="select__item select__item_size">{{s.size}}</div>
                                            {% endif %}
                                        {% endfor %}
                                </div>
                            </div>

                            <div class="select color-select">
                                <div class="select__header select__header_color">
                                    <span class="select__current select__current_color">{% trans 'Color' %}</span>
                                </div>
                                <input type="hidden" class="chosen-color {{item.id}}" name="chosen-color" value="{{item.id}}=">
                                <div class="select__body select__body_color">
                                    {% for color in colors %}
                                            {% if color.product_id == item.id %}
                                                <div class="select__item select__item_color">{{color.color_name}}</div>
                                            {% endif %}
                                        {% endfor %}
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="discount-section">
        <span>{% trans 'Chosen items' %} : <span class="chosen-items"></span></span><br>
        <span>{% trans 'Discount' %} :<span class="discount-percent"></span></span><br>
        <span>{% trans 'Items price with discount' %}: <span class="discount-price"></span> {% trans 'UAH' %} </span><br>

            <input type="hidden" class="hidden-price" name="discount-price">
            <input type="hidden" class="hidden-percent" name="discount-percent">
            <input type="hidden" class="hidden-ids" name="discount-ids">
            <input type="hidden" name="gender" value="{{gender}}">
            <input type="hidden" name="url_from" value="{{request.path}}">
            <p><button type="submit" class="col-buy-button">{% trans 'Make order' %}</button></p>


    </div>
</div>
</form>
{% else %}

<div class="empty-page-logo">
        <img src="/static/mainFront/img/empty.svg">
    </div>

<div class="empty-page-title"> {% trans 'No products in collection' %} "{{ col_name }}" :( </div>
    <div style="text-align: center; margin-bottom: 45px">
		<a href="{% url 'collection:collection' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'GO BACK' %}
			</div>
		</a>
	</div>
{% endif %}
<link rel="stylesheet" href="{% static 'collection/css/sizes.css' %}">
<script src="{% static 'collection/js/sizes.js' %}"></script>

{% endblock %}