FrontendPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('shop/', include('product.urls')),
    path('contacts/', include('contacts.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('news/', include('news.urls')),
    path('', include('mainFront.urls')),
    path('collection/', include('collection.urls')),
    path('order/', include('order.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.Collections.as_view(), name='collection'),
    path('buy_collection', views.buy_collection, name='buy_collection'),
    path('<slug:slug>/<str:gender>/', views.SliderCollection.as_view(), name='slider_collection'),
    path('make_col_order/', views.make_col_order, name='make_col_order'),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.MyNews.as_view(), name='news'),
    path('<slug:slug>/', views.load_news, name='load_news'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('make_order/', views.make_order2, name='make_order'),
    path('completed_orders/', views.completed_orders, name='completed_orders'),
    path('completed_detail/<int:pk>/', views.completed_detail, name='completed_detail'),
    path('completed_col_detail/<int:pk>/', views.completed_col_detail, name='completed_col_detail'),
    path('change_quantity/', views.change_quantity, name='change_quantity'),
    path('remove_item_from_cart/', views.remove_item_from_cart, name='remove_item_from_cart'),
    ]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('<slug:slug>/', views.CategoriesItems.as_view(), name='categories'),
    path('<str:gender>/<slug:cat_slug>/<slug:prod_slug>/', views.product_detail, name='product_detail'),
]

product/models.py
from django.db import models
from collection.models import Collection
from .const import GENDER_CHOICES, SIZE_CHOICES


class Product(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, default=None, blank=True, null=True)
    category = models.ForeignKey('ProductCategory', on_delete=models.CASCADE, default=None, blank=True, null=True)
    title = models.CharField(max_length=128, verbose_name='Название')
    slug = models.SlugField(max_length=128, unique=True, db_index=True, verbose_name='URL')
    price = models.IntegerField(verbose_name='Цена')
    description = models.TextField(verbose_name='Описание')
    main_image = models.ImageField(upload_to='product_img/', verbose_name='Изображение', default='333')
    in_stock = models.BooleanField(default=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default=None, verbose_name='Раздел')
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return "id={}, title={}, price='{}'".format(self.id, self.title, self.price)

    class Meta:
        ordering = ['id']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='product_img/', verbose_name='Изображение')
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    def __str__(self):
        return 'imageId:{} => to ProductId{}'.format(self.product_id, self.id)


class ProductSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    size = models.CharField(max_length=20, choices=SIZE_CHOICES, default=0)

    class Meta:
        verbose_name = "Size"
        verbose_name_plural = "Sizes"

    def __str__(self):
        return 'pr_name: {}, size: {}'.format(self.product_id, self.size)


class ProductColor(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    color_name = models.CharField(max_length=20, default='white')

    class Meta:
        verbose_name = "Color"
        verbose_name_plural = "Colors"

    def __str__(self):
        return self.color_name


class ProductCategory(models.Model):
    category = models.CharField(max_length=15)
    slug = models.SlugField(max_length=30, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category

product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from django.views.decorators.cache import cache_page

from product.models import Product, ProductSize, ProductCategory, ProductImage, ProductColor



def shop(request):
    categories = ProductCategory.objects.all()
    return render(request, 'product/shop.html', {'categories': categories})


class Shop(ListView):
    model = ProductCategory
    template_name = 'product/shop.html'
    context_object_name = 'categories'


class CategoriesItems(ListView):
    model = Product
    template_name = 'product/category.html'
    context_object_name = 'products'

    # get all objects with chosen category

    def get_queryset(self, **kwargs):
        global cat_slug
        cat_slug = self.kwargs['slug']
        return Product.objects.filter(category__slug=cat_slug, in_stock=True).select_related('category')

    # get chosen category name for title of page

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = ProductCategory.objects.get(slug=cat_slug)
        context['cat_name'] = cat.category
        return context


def product_detail(request, gender, cat_slug, prod_slug):

    # Get all products with chosen gender and category
    products = Product.objects.filter(category__slug=cat_slug, gender=gender, in_stock=True)

    # And get chosen product by slug
    current_obj = get_object_or_404(Product, slug=prod_slug)

    # Get all sizes for this product
    size = ProductSize.objects.filter(product__slug=prod_slug)

    # Now we splitting QuerySet to place 1 object on 1 page

    paginator = Paginator(products, 1)
    if current_obj in products:
        current_page = list(products).index(current_obj) + 1
    else:
        response = render(request, 'mainFront/page404.html')
        response.status_code = 404
        return response
    page_obj = paginator.get_page(current_page)
    if page_obj.has_previous():
        prev_slug = (products[current_page-2]).slug
    else:
        prev_slug = None
    if page_obj.has_next():
        next_slug = (products[current_page]).slug
    else:
        next_slug = None

    # Get all images ans colors of current object

    images = ProductImage.objects.filter(product__slug=prod_slug)
    colors = ProductColor.objects.filter(product__slug=prod_slug)
    return render(request, 'product/product_detail.html',
                  {'page_obj': page_obj,
                   'prev_slug': prev_slug,
                   'gender': gender,
                   'cat_slug': cat_slug,
                   'next_slug': next_slug,
                   'size': size,
                   'colors': colors,
                   'images': images})

product/templates/product/category.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Shop{%endblock%}
{% load i18n %}
{% block content %}
{% if products %}
    <h1 style="text-align: center; margin-top: 90px;  font-size: 26px;">{{cat_name}}</h1>

    <div class="categories_nav" style>
		<button class="cat-nav-but chosen_cat_button" value="mens">{% trans 'Men' %}</button>
		<button class="cat-nav-but" value="womens">{% trans 'Women' %}</button>
		<button class="cat-nav-but" value="kids">{% trans 'Kids' %}</button>
	</div>
	<div class="cat-wrapper">
				<div class="mens_products z-class1">
					{% for item in products%}
						{% if item.gender == 'man' %}
							<div class="cat-item">
								<a href="{% url 'product:product_detail' item.gender item.category.slug item.slug %}">
									<div class="cat-image">
										<img class="cat-image-img" src="{{ item.main_image.url }}" alt="ZXC">
									</div>
									<div class="cat-desc">
										<span class="cat-title"> {{item.title}} </span>
										
										<div class="bookmark-box" data-id="{{item.id}}">
											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart-fill bookmarks-hart-fill"  viewBox="0 0 16 16">
												<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
											</svg>

											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart bookmarks-hart-empty" viewBox="0 0 16 16">
												<path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
											</svg>

				                        </div>
									</div>
								</a>
							</div>

						{%endif%}
					{% endfor %}
				</div>

				<div class="womens_products z-class0">
					{% for item in products %}
						{% if item.gender == 'woman' %}
							<div class="cat-item">
								<a href="{% url 'product:product_detail' item.gender item.category.slug item.slug %}">
									<div class="cat-image">
										<img class="cat-image-img" src="{{ item.main_image.url }}" alt="ZXC">
									</div>
									<div class="cat-desc">
										<span class="cat-title"> {{item.title}} </span>
										<div class="bookmark-box" data-id="{{item.id}}">
											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart-fill bookmarks-hart-fill"  viewBox="0 0 16 16">
												<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
											</svg>

											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart bookmarks-hart-empty" viewBox="0 0 16 16">
												<path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
											</svg>

				                        </div>
									</div>
								</a>
							</div>

						{%endif%}
					{% endfor %}
				</div>

				<div class="kids_products z-class0">
					{% for item in products%}
						{% if item.gender == 'kid' %}
							<div class="cat-item">
								<a href="{% url 'product:product_detail' item.gender item.category.slug item.slug %}">
									<div class="cat-image">
										<img class="cat-image-img" src="{{ item.main_image.url }}" alt="ZXC">
									</div>
									<div class="cat-desc">
										<span class="cat-title"> {{item.title}} </span>
										<div class="bookmark-box" data-id="{{item.id}}">
											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart-fill bookmarks-hart-fill"  viewBox="0 0 16 16">
												<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
											</svg>

											<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#dd5145" class="bi bi-heart bookmarks-hart-empty" viewBox="0 0 16 16">
												<path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
											</svg>

				                        </div>
									</div>
								</a>
							</div>

						{%endif%}
					{% endfor %}
				</div>

	</div>

{% else %}
	
	<div class="empty-page-logo">
        <img src="/static/mainFront/img/empty.svg">
    </div>

    <div class="empty-page-title">{% trans 'Still no products in category' %} "{{cat_name}}"</div>

{% endif %}
<div style="text-align: center; margin-top: 10px; margin-bottom: 40px">
		<a href="{% url 'product:shop' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'ALL CATEGORIES' %}
			</div>
		</a>
	</div>

{% endblock %}


product/templates/product/product_detail.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Sweatshirts{%endblock%}
{% load i18n %}
{% block content%}


<div class="detail_wrapper">
{% for i in page_obj %}

    <div style="margin-top: 100px; font-size: 35px; font-weight:bolder; text-align: center;"> {{ i.title }} </div>
        <div class="image-box-wrapper">
            <div class="image_box">
                {% for image in images %}
                    <div class="image-wrapper">
                        <img src="{{ image.picture.url }}">
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="product_details_box">



            <form method="post" action="{% url 'order:add_to_cart' %}" id="size_choise" class="form-inline">
                {% csrf_token %}

                <div class="red-wrapper">
                    
                    <span class="single-price">
                        {{i.price}} {% trans 'UAH' %}
                    </span>

                    <div class="bookmark-box" data-id="{{i.id}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#dd5145" class="bi bi-heart-fill bookmarks-hart-fill"  viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                            </svg>

                                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#dd5145" class="bi bi-heart bookmarks-hart-empty" viewBox="0 0 16 16">
                                                  <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                                </svg>

                                        </div>
                </div>

                <div class="select-fields-wrapper">
                    <select form="size_choise" name="color" id="color" class="single-select-form">
                        {% for c in colors %}
                                <option value="{{c.color_name}}" typeof="color" class="single-option-form">{{c.color_name}}</option>
                        {% endfor %}
                    </select>

                    <select form="size_choise" name="size" id="size" class="single-select-form">
                        {% for s in size%}
                                <option  value="{{s.size}}" class="single-option-form">{{s.size}}</option>
                        {% endfor %}
                    </select>

                    <button id="submit_button" class="single-button" type="submit"
                        data-product_id="{{i.id}}"
                        data-product_title="{{i.title}}"
                        data-product_price="{{i.price}}"
                        data-product_image="{{i.main_image}}">{% trans 'Buy' %}
                    </button>
                </div><br>



            </form>

             <div class="single-description">
                <span>{{ i.description }}</span>

            </div>

        </div>

    <div style="margin-bottom: 40px">
        <div class="single-bot-link-wrapper">
        {% if prev_slug != None %}
            <a  style="text-decoration: none;" href="{% url 'product:product_detail' gender cat_slug prev_slug %}">
                <div class="single-bot-link">{% trans 'Previous product' %}</div></a>
        {% endif %}
        {% if next_slug != None %}
            <a style="text-decoration: none;" href="{% url 'product:product_detail' gender cat_slug next_slug %}">
                <div class="single-bot-link">{% trans 'Next product' %}</div></a>
        {% endif %}
        </div>
        <div class="single-bot-link-wrapper">
            <a style="text-decoration: none;" href="{% url 'product:categories' i.category.slug %}"><div class="single-bot-link to-shop">{% trans 'To shop' %}</div></a>
            {% if i.collection.slug %}
                <a style="text-decoration: none;" href="{% url 'collection:slider_collection' i.collection.slug gender %}"><div class="single-bot-link to-shop">{% trans 'See in collection' %}</div></a>
            {% endif %}
        </div>
    </div>
{% endfor %}
</div>


{% endblock %}

product/templates/product/shop.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Shop{%endblock%}
{% load i18n %}
{% block content %}
<h1 style="text-align: center; margin-top: 90px;  font-size: 26px;">{% trans 'OUR PRODUCTS' %}</h1>
<div class="all_categories">
    {% for cat in categories %}
        <p><a class="cat_href" href="{% url 'product:categories' cat.slug %}">
            <span class="cat">
                {{ cat.category }}
            </span>
        </a></p>
    {% endfor%}
</div>
{% endblock %}    