FrontendPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('shop/', include('product.urls')),
    path('contacts/', include('contacts.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('news/', include('news.urls')),
    path('', include('mainFront.urls')),
    path('collection/', include('collection.urls')),
    path('order/', include('order.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.urls import path
from . import views

app_name = 'bookmarks'
urlpatterns = [
    path('', views.bookmarks, name='bookmarks'),
    path('add/', views.add_to_bookmarks, name='add_to_bookmarks'),
    path('remove/', views.remove_from_bookmarks, name='remove_from_bookmarks'),
    path('delete/', views.remove_bookmarks, name='remove_bookmarks'),
    path('api/', views.bookmarks_api, name='bookmarks_api'),
]

collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.Collections.as_view(), name='collection'),
    path('buy_collection', views.buy_collection, name='buy_collection'),
    path('<slug:slug>/<str:gender>/', views.SliderCollection.as_view(), name='slider_collection'),
    path('make_col_order/', views.make_col_order, name='make_col_order'),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.MyNews.as_view(), name='news'),
    path('<slug:slug>/', views.load_news, name='load_news'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('<slug:slug>/', views.CategoriesItems.as_view(), name='categories'),
    path('<str:gender>/<slug:cat_slug>/<slug:prod_slug>/', views.product_detail, name='product_detail'),
]

bookmarks/models.py
from django.db import models

# Create your models here.

bookmarks/views.py
from django.shortcuts import render, redirect
from product.models import Product
from django.http import JsonResponse


def bookmarks(request):
    liked_items = request.session.get('bookmarks')
    bookmarks_list = list()
    print('liked: ', liked_items)
    if liked_items:
        for i in liked_items:
            try:
                liked = Product.objects.filter(id=int(i), in_stock=True)
                if liked:
                    bookmarks_list.append(liked[0])

                # bookmarks_list.append(Product.objects.get(id=int(i)))
            except Exception as ex:
                print(ex, 'No product with ID {} in DB'.format(i))
                request.session['bookmarks'].remove(i)
                request.session.modified = True
        print(bookmarks_list)
    return render(request, 'bookmarks/bookmarks.html', {'bookmarks': bookmarks_list})


def add_to_bookmarks(request):
    print('we are here')
    if request.method == 'POST':
        print('adding', request.POST)
        if not request.session.get('bookmarks'):
            request.session['bookmarks'] = list()
        else:
            request.session['bookmarks'] = list(request.session['bookmarks'])

        # chek if item exists
        item_exists = next((item for item in request.session['bookmarks'] if item == request.POST.get('id')), False)

        if not item_exists:
            request.session['bookmarks'].append(request.POST.get('id'))
            request.session.modified = True
    if request.is_ajax:
        data = {'id': request.POST.get('id')}
        print('ajax')
        print('request: ', request)
        request.session.modified = True
        return JsonResponse(data)

    return redirect(request.POST.get('url_from'))


def remove_from_bookmarks(request):
    print('we got removeRequest')
    if request.method == 'POST':
        request.session['bookmarks'].remove(request.POST.get('id'))
        request.session.modified = True

    if request.is_ajax:
        counter = len(request.session['bookmarks'])
        request.session.modified = True
        data = {'id': request.POST.get('id'), 'counter': counter}
        return JsonResponse(data)

    return redirect(request.POST.get('url_from'))


def remove_bookmarks(request):
    if request.session.get('bookmarks'):
        del request.session['bookmarks']
        request.session.modified = True
        return redirect(request.POST.get('url_from'))


def bookmarks_api(request):
    return JsonResponse(request.session.get('bookmarks'), safe=False)

bookmarks/templates/bookmarks/bookmarks.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}order{%endblock%}
{% load i18n %}
{% block content%}
{% if bookmarks %}
    <h1 style="text-align: center; margin-top: 90px;  font-size: 26px;">{% trans 'BOOKMARKS' %}</h1>

{% for item in bookmarks %}
<div class="bookmarks-wrapper">
    <div class="bookmark_item">
        <div class="bookmark_img">
            <img src="{{ item.main_image.url }}">
        </div>
        <div class="bookmark_details_wrapper">
            <div class="bookmark_details">
                <p><span>{% trans 'Title' %}: {{item.title}}</span></p>
                <p><span>{% trans 'Price' %}: {{item.price}}</span></p>
                {% if item.collection %}
                    <p><span>{% trans 'Collection' %}: {{item.collection}}</span></p>
                {% endif %}
            </div>
        </div>
        <div class="bookmark_options">

                <button class="buy_from_bookmark_button" type="submit">
                    <a href="{% url 'product:product_detail' item.gender item.category.slug item.slug%}">{% trans 'View' %} </a></button>

            <button class="remove_from_bookmark_button" type="submit" data-id="{{item.id}}">{% trans 'Remove' %}</button>
        </div>

    </div>

</div>
{% endfor %}

<form action="{% url 'bookmarks:remove_bookmarks' %}" method="post">{% csrf_token %}

                    <input type="hidden" name="url_from" value="{{request.path}}">
                    <div style="text-align: center; margin-bottom: 30px;">
                        <button class="remove_book_but" type="submit">{% trans 'Remove all' %}</button>
                    </div>
                </form>
{% else %}
    

    <div class="empty-page-logo">
        <img src="/static/mainFront/img/empty.svg">
    </div>

    <div class="empty-page-title">{% trans 'YOUR BOOKMARKS LIST IS EMPTY' %}</div>

    <div style="text-align: center; margin-bottom: 45px;">
		<a href="{% url 'product:shop' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'TO SHOP' %}
			</div>
		</a>

        <a href="{% url 'collection:collection' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'TO COLLECTIONS' %}
			</div>
		</a>
	</div>
{% endif %}
{% endblock %}

bookmarks/templates/bookmarks/delete_me.html
 <form action="{% url 'bookmarks:add_to_bookmarks' %}" method="post">{% csrf_token %}
                    <input type="hidden" name="id" value="{{i.id}}">
                    <input type="hidden" name="url_from" value="{{request.path}}">
                    <button type="submit" style="background: none; border:none; margin-left: 120px; margin-top: -20px">
                        <svg  id="zxc" data-id="zxc" xmlns="http://www.w3.org/2000/svg" width="26" height="24" fill="#02520B" class="bi bi-heart-fill empty_hart" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                            </svg></button>
                </form>
                <form action="{% url 'bookmarks:remove_from_bookmarks' %}" method="post">{% csrf_token %}
                    <input type="hidden" name="id" value="{{i.id}}">
                    <input type="hidden" name="url_from" value="{{request.path}}">
                    <button type="submit" style="background: none; border:none; margin-left: 120px; margin-top: -20px">
                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="24" fill="#02520B" class="bi bi-heart-fill full_hart" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                            </svg></button>
                </form>

 <div class="bookmarks" data-id={{i.id}}>