FrontendPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('shop/', include('product.urls')),
    path('contacts/', include('contacts.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('news/', include('news.urls')),
    path('', include('mainFront.urls')),
    path('collection/', include('collection.urls')),
    path('order/', include('order.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.Collections.as_view(), name='collection'),
    path('buy_collection', views.buy_collection, name='buy_collection'),
    path('<slug:slug>/<str:gender>/', views.SliderCollection.as_view(), name='slider_collection'),
    path('make_col_order/', views.make_col_order, name='make_col_order'),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.MyNews.as_view(), name='news'),
    path('<slug:slug>/', views.load_news, name='load_news'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('make_order/', views.make_order2, name='make_order'),
    path('completed_orders/', views.completed_orders, name='completed_orders'),
    path('completed_detail/<int:pk>/', views.completed_detail, name='completed_detail'),
    path('completed_col_detail/<int:pk>/', views.completed_col_detail, name='completed_col_detail'),
    path('change_quantity/', views.change_quantity, name='change_quantity'),
    path('remove_item_from_cart/', views.remove_item_from_cart, name='remove_item_from_cart'),
    ]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('<slug:slug>/', views.CategoriesItems.as_view(), name='categories'),
    path('<str:gender>/<slug:cat_slug>/<slug:prod_slug>/', views.product_detail, name='product_detail'),
]

order/models.py
from django.db import models
from product.models import Product
from django.db.models.signals import post_delete
from .const import DELIVERY_REGIONS


class Order(models.Model):
    status = models.ForeignKey('Status', on_delete=models.CASCADE)
    user = models.CharField(max_length=200, blank=True, null=True, default='user')
    order_price = models.IntegerField()
    delivery_price = models.IntegerField(null=True, default=0)
    customer_name = models.CharField(max_length=28)
    customer_email = models.EmailField()
    customer_phone = models.CharField(max_length=28)
    delivery_region = models.CharField(max_length=40, choices=DELIVERY_REGIONS, default=None)
    delivery_district = models.CharField(max_length=40, default=None, blank=True)
    delivery_city = models.CharField(max_length=40, default=None)
    nova_poshta_departament = models.SmallIntegerField(default=None)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return 'Order id =' + str(self.id)

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    size = models.CharField(max_length=10, default='Universal')
    color = models.CharField(max_length=20, default='white', null=True)
    quantity = models.PositiveIntegerField(default=1)
    price_per_item = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = "Product in Order"
        verbose_name_plural = "Products in Order"

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.total_price = self.quantity * self.price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)


def post_delete_product_in_order(sender, instance, *args, **kwargs):
    all_products_in_order = ProductInOrder.objects.filter(order=instance.order, is_active=True)
    order_price = 0
    for product in all_products_in_order:
        order_price += product.total_price

    instance.order.order_price = order_price
    instance.order.save(force_update=True)


post_delete.connect(post_delete_product_in_order, sender=ProductInOrder)


class ProductInBasket(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True, default=None)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=140)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=30)
    color = models.CharField(max_length=20, default='white', null=True)
    price_per_item = models.IntegerField(default=0)
    product_total_price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return 'Product[{}], size={}'.format(self.product, self.size)

    class Meta:
        verbose_name = "Product in Basket"
        verbose_name_plural = "Products in Basket"

    # Calculating price for certain product to show it in cart

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.product_total_price = int(self.quantity) * int(self.price_per_item)

        super(ProductInBasket, self).save(*args, **kwargs)


# Order as collection

class CollectionOrder(models.Model):
    user = models.CharField(max_length=200, blank=True, null=True, default='user')
    order_price = models.IntegerField()
    discount_percent = models.CharField(max_length=10)
    customer_name = models.CharField(max_length=28)
    customer_email = models.EmailField()
    customer_phone = models.CharField(max_length=28)
    status = models.ForeignKey('Status', on_delete=models.CASCADE)
    delivery_region = models.CharField(max_length=40, choices=DELIVERY_REGIONS, default=None)
    delivery_district = models.CharField(max_length=40, default=None, blank=True)
    delivery_city = models.CharField(max_length=40, default=None)
    nova_poshta_departament = models.SmallIntegerField(default=None)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return 'ColOrder id =' + str(self.id)


class ProductInCollectionOrder(models.Model):
    col_order = models.ForeignKey(CollectionOrder, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    size = models.CharField(max_length=10, default='Universal')
    color = models.CharField(max_length=20, default='white', null=True)
    price_per_item = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return self.product.title


class Status(models.Model):
    status = models.CharField(max_length=40)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Status"

order/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import ProductInBasket, Order, ProductInOrder, CollectionOrder, ProductInCollectionOrder, Status
from .tg import telegram_bot_send_order_text
from .mail import send_email


def cart_products_counter(session_key):
    counter = ProductInBasket.objects.filter(session_key=session_key, product__in_stock=True).count()
    print(counter, 'products in cart')
    return {'products_counter': counter}


def get_session_key(request):
    session_key = request.session.session_key
    if not session_key:
        session_key = 123
        session_key = request.session.cycle_key()
    return session_key


def add_to_cart(request):
    data = request.POST
    print(data)
    product_id = data.get('product_id')
    size = data.get('product_size')
    color = data.get('product_color')
    price = data.get('product_price')
    session_key = get_session_key(request)

    # trying to find product in cart
    # if it in cart we are increase quantity by 1

    search = ProductInBasket.objects.filter(session_key=session_key, product_id=product_id, size=size, color=color).count()
    if search:
        product = ProductInBasket.objects.get(
            session_key=session_key, product_id=product_id, size=size, price_per_item=price)
        product.quantity += 1
        product.save()
    else:
        ProductInBasket.objects.create(
            session_key=session_key, product_id=product_id, size=size, price_per_item=price, color=color).save()

    return JsonResponse(cart_products_counter(session_key))


def cart(request):
    session_key = get_session_key(request)
    cart_items = ProductInBasket.objects.filter(session_key=session_key, product__in_stock=True).select_related \
    ('product', 'product__category')
    return render(request, 'order/cart.html', {'cart_items': cart_items})


def make_order2(request):
    data = request.POST
    if request.method == 'POST':
        user = get_session_key(request)
        customer_name = data.get('customer_name')
        customer_email = data.get('customer_email')
        customer_phone = data.get('customer_phone')
        order_price = int(data.get('hidden_total'))
        delivery_price = int(data.get('delivery_price'))
        delivery_region = data.get('delivery_region')
        delivery_district = data.get('delivery_district')
        delivery_city = data.get('delivery_city')
        nova_poshta_departament = data.get('nova_poshta')
        comment = data.get('comment')
        order = Order.objects.create(
            user=user,
            order_price=order_price,
            delivery_price=delivery_price,
            customer_name=customer_name,
            customer_email=customer_email,
            customer_phone=customer_phone,
            delivery_region=delivery_region,
            delivery_district=delivery_district,
            delivery_city=delivery_city,
            nova_poshta_departament=nova_poshta_departament,
            comment=comment,
            status=Status.objects.get(id=1)
        )
        for item in data:
            if item.startswith('product_in_cart'):
                item_id = int(item.split('product_in_cart_')[1])
                try:
                    product_in_cart = ProductInBasket.objects.filter(id=item_id)[0]

                    ProductInOrder.objects.create(order=order,
                                                  product=product_in_cart.product,
                                                  size=product_in_cart.size,
                                                  color=product_in_cart.color,
                                                  quantity=product_in_cart.quantity,
                                                  price_per_item=product_in_cart.price_per_item,
                                                  total_price=product_in_cart.product_total_price
                                                  )
                    product_in_cart.delete()
                except IndexError:
                    return redirect(data.get('url_from'))

        # Code for telegram notification

        telegram_bot_send_order_text(order=order, products=ProductInOrder.objects.filter(order_id=order.id).select_related('product'))
        print(send_email(order, '{}/order/completed_detail/{}'.format(request.get_host(), order.id)))
        redirect_url = data.get('url_from')
        return redirect('{}completed_detail/{}'.format(redirect_url[:-5], order.id))
    return HttpResponse(request.POST)


def change_quantity(request):
    quantity = request.POST.get('quantity')
    pk = request.POST.get('item_id')
    item = ProductInBasket.objects.get(id=pk)
    item.quantity = quantity
    item.save()
    return JsonResponse({})


def remove_item_from_cart(request):
    pk = request.POST.get('item_id')
    ProductInBasket.objects.filter(id=pk).delete()
    # Lets change product counter directly
    return JsonResponse(cart_products_counter(get_session_key(request)))


def completed_orders(request):
    users_orders = reversed(Order.objects.filter(user=get_session_key(request)))
    users_col_orders = reversed(CollectionOrder.objects.filter(user=get_session_key(request)))
    return render(request, 'order/completed.html', {'orders': users_orders, 'col_orders': users_col_orders})


def completed_detail(request, pk):
    order = ProductInOrder.objects.filter(order_id=pk).select_related('product')
    return render(request, 'order/completed_detail.html', {'order': order, 'order_id': pk})


def completed_col_detail(request, pk):
    order = ProductInCollectionOrder.objects.filter(col_order_id=pk).select_related('product')
    return render(request, 'order/completed_detail.html', {'order': order, 'order_id': pk})

order/templates/order/cart.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}Cart{%endblock%}
{% load i18n %}
{% block content%}
{% if cart_items %}
    <h1 style="text-align: center; margin-top: 90px;  font-size: 26px;">{% trans 'YOUR PRODUCTS' %} </h1>

    <form id="order_form" method="post" action="{% url 'order:make_order' %}"> {% csrf_token %}
        <div class="cart-item-wrapper">

             
            {% for item in cart_items %}
                <div class="cart_item">
                    <div class="cart_product_img">
                        <img src="{{item.product.main_image.url}}">
                    </div>
                    <div class="cart_item_fields">
                        <label>{% trans 'Item name:' %}&nbsp </label>
                            <a href="{% url 'product:product_detail' item.product.gender item.product.category.slug item.product.slug %}"
                            class="cart-details-link"> {{ item.product.title }} </a><br>

                        {% trans 'Item size'%}:  <span style="color: #dd5145; font-weight:500"> {{ item.size }}</span><br>
                        {% trans 'Item color' %}:  <span style="color: #dd5145; font-weight:500"> {{ item.color }}</span><br>
                        {% trans 'Item price' %}: <span style="color: #dd5145; font-weight:500" class="price_for_item" data-item_id="{{item.id}}">{{ item.price_per_item}} {% trans 'UAH' %}</span><br>
                        {% trans 'Total price' %}: <span class="product_total_price" style="color: #dd5145; font-weight:500">{{ item.product_total_price }}</span>
                        <span style="color: #dd5145; font-weight:500">   {% trans 'UAH' %}</span><br>
                        <button class="basket-quantity__btn minus" type="button">
                            <span class="fas fa-chevron-left"></span>
                        </button>    
                        <input value="{{ item.quantity }}" type="tel" min="1" class="product_quantity"
                               name="product_in_cart_{{ item.id }}">
                       <button class="basket-quantity__btn plus" type="button">
                            <span class="fas fa-chevron-right"></span>
                        </button> 
                        <span class="item_id" style="display: none;">{{ item.id }}</span>
                    </div>
                    <button type="button" class="remove_product_button">X</button>
                </div>
            {% endfor %}
        </div>

        <div class="user-data-wrapper">
            <div class="customer_data">

                <div class="form1">
                    <h4 style="margin-bottom: 20px">{% trans 'Order form' %}</h4>

                    <input class="form1-group" name="customer_name" type="text" placeholder="{% trans 'name' %}" required><br>
                    <input class="form1-group" name="customer_email" type="email" placeholder="emailExample@gmail.com" required><br>
                    <input class="form1-group" data-tel-input name="customer_phone" maxlength="19" type="tel" placeholder="{% trans 'phone' %}" required><br><br>

                    <div class="order_price">
                    <div>{% trans 'Products price' %}: <span class="calculated_products_price" ></span>
                    <span style="color: #dd5145; font-weight:500"> {% trans 'UAH' %}</span></div>
                    <div>{% trans 'Delivery price' %}: <span class="delivery_price"></span>
                        <span style="color: #dd5145; font-weight:500">{% trans 'UAH' %}</span></div>
                    <div>{% trans 'Total order price' %}: <span class="calculated_order_price" ></span>
                    <span style="color: #dd5145; font-weight:500"> {% trans 'UAH' %}</span> </div>

                    </div><br><br>
                    <label style="font-size: 18px; ">{% trans 'Delivery info' %}</label><br><br>
                    <select name="delivery_region" class="delivery_region form1-group">
                        <option value="VINNYTSKA OBL">Вiнницька область</option>
                        <option value="VOLYNSKA OBL">Волинська область</option>
                        <option value="DNIPROPETROVSKA OBL">Днiпропетровська область</option>
                        <option value="DONETSKA OBL">Донецька область</option>
                        <option value="JYTOMYRSKA OBL">Житомирська область</option>
                        <option value="ZAKARPATSKA OBL">Закарпатська область</option>
                        <option value="ZAPORIJSKA OBL">Запорiжська область</option>
                        <option value="IVANO FRANKIVSKA OBL">Iвано-Франкiвська область</option>
                        <option value="KYIVSKA OBL">Київська область</option>
                        <option value="KIROVOGRADSKA OBL">Кiровоградська область</option>
                        <option value="LUHANSKA OBL">Луганська область</option>
                        <option value="LVIVSKA OBL">Львiвська область</option>
                        <option value="MYKOLAIVSKA OBL">Миколаївська область</option>
                        <option value="ODESKA OBL">Одеська область</option>
                        <option value="POLTAVSKA OBL">Полтавська область</option>
                        <option value="RIVNENSKA OBL">Рiвненська область</option>
                        <option value="SUMSKA OBL">Сумська область</option>
                        <option value="TERBOPILSKA OBL">Тернопiльська область</option>
                        <option value="KHARKIVSKA OBL">Харкiвська область</option>
                        <option value="KHERSONSKA OBL">Херсонська область</option>
                        <option value="KHMELNYTSKA OBL">Хмельницька область</option>
                        <option value="CHERKASKA OBL">Черкаська область</option>
                        <option value="CHERNIHIVSKA OBL">Чернiгiвська область</option>
                        <option value="CHERNIVETSKA OBL">Чернiвецька область</option>
                    </select><br>

                    <input class="form1-group" name="delivery_district" type="text" placeholder="{% trans 'district (optional)' %}"><br>
                    <input class="form1-group" name="delivery_city" type="text" placeholder="{% trans 'city or town' %}" required><br>
                    <input class="form1-group" name="nova_poshta" type="number" placeholder="{% trans 'nova poshta №' %}" min="1" required><br>
                    <input class="form1-group" name="comment" type="textarea" size="60" placeholder="{% trans 'comment (optional)' %}"><br>
                    <input type="hidden" name="url_from" value="{{request.path}}">
                    <input class="hidden_total" type="hidden" name="hidden_total">
                    <input class="hidden_delivery_price" type="hidden" name="delivery_price">
                    <div class="checkbox">
                        <input class="checkbox__input" type="checkbox" name="agreement" required id="agreement">
                        <label class="checkbox__label" for="agreement">{% trans 'I agree with data processing rules' %}</label>
                    </div>
                    <div class="checkout-wrapper">
                        <button  type="submit" class="form1-submit_button" >{% trans 'Checkout' %}</button>
                    </div>
                </div>
            </div>

        </div>
    </form>

    <script src="{% static 'mainFront/js/inputMask.js' %}"></script>
{% else %}

    <div class="empty-page-logo">
        <img src="/static/mainFront/img/empty.svg">
    </div>

    <div class="empty-page-title"> {% trans 'YOUR CART IS EMPTY' %}</h3>

    <div style="text-align: center; margin-bottom: 45px">
		<a href="{% url 'product:shop' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'TO SHOP' %}
			</div>
		</a>

        <a href="{% url 'collection:collection' %}" class="back-to-cats-a">
			<div class="back-to-cats">
				{% trans 'TO COLLECTIONS' %}
			</div>
		</a>
	</div>
{% endif %}



{% endblock %}

order/templates/order/completed.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}order{%endblock%}
{% load i18n %}
{% block content%}
<h1 style="text-align: center; margin-top: 90px;  font-size: 26px;"> {% trans 'MY ORDERS' %} </h1>

<div class="completed-nav" style>
		<button type="button" class="completed-nav-but1 chosen_completed_button" >{% trans 'as product' %}</button>
		<button type="button" class="completed-nav-but2">{% trans 'as collection' %}</button>

	</div>
<div class="completed-orders-wrapper">
    <div class="com-order-wrap z-class1 swipe-in">
        {% for item in orders %}
        <div class="completed_order">
            <span>{% trans 'ORDER ID' %}: {{item.id}}</span><br>
            <span>{% trans 'CREATED' %}: {{ item.created }}</span><br>
            <span>{% trans 'ORDER PRICE' %}: {{ item.order_price }} {% trans 'UAH' %}</span><br>
            <span>{% trans 'DELIVERY PRICE' %}: {{ item.delivery_price }} {% trans 'UAH' %}</span><br>
            <span>{% trans 'ORDER STATUS' %}: {{ item.status }}</span>
            <a href="{% url 'order:completed_detail' item.id %}"><button class="completed-button" type="submit">{% trans 'View details' %}</button> </a>
            <hr>
        </div>
        {% endfor %}
    </div>
    <div class="com-c-order-wrap z-class0">
        {% for item in col_orders %}
        <div class="completed_c_order">
            <span>{% trans 'ORDER ID' %}: {{item.id}}</span><br>
            <span>{% trans 'CREATED' %}: {{ item.created }}</span><br>
            <span>{% trans 'ORDER PRICE' %}: {{ item.order_price }} {% trans 'UAH' %}</span><br>
            <span>{% trans 'DISCOUNT FOR THIS ORDER' %}: {{ item.discount_percent }}</span><br>
            <span>{% trans 'ORDER STATUS' %}: {{ item.status }}</span>
            <a href="{% url 'order:completed_col_detail' item.id %}"><button class="completed-button" type="submit">{% trans 'View details' %}</button> </a>
            <hr>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

order/templates/order/completed_detail.html
{% extends 'mainFront/base.html' %}
{% load static %}
{% block title %}order{%endblock%}
{% load i18n %}
{% block content%}
<h1 style="text-align: center; margin-top: 90px;  font-size: 26px;"> {% trans 'Order ID' %}: {{order_id}} </h1>
<div class="comp-det-wrap-wrapper">
    <div class="completed-detail-wrapper">
    {% for item in order %}
            <div class="item_in_order">
                <div class="completed_img">
                    <img src="{{item.product.main_image.url}}">
                </div>
                <div class="completed_info">
                    <span class="comp completed_title">{% trans 'Title' %}: {{ item.product.title }}</span><br>
                    {% if item.quantity %}
                    <span class="comp completed_price"> {% trans 'Price per item' %}: {{ item.product.price }} {% trans 'UAH' %}  x {{ item.quantity }}</span><br>
                    {% else %}
                    <span class="comp completed_price"> {% trans 'Price per item' %}: {{ item.product.price }} {% trans 'UAH' %}</span><br>
                    {% endif %}
                    <span class="comp completed_size"> {% trans 'Size' %}: {{ item.size }}</span><br>
                    <span class="comp completed_size"> {% trans 'Color' %}: {{ item.color }}</span><br>
                    {% if item.total_price %}
                    <span class="comp completed_size">{% trans 'total' %}: {{ item.total_price }} {% trans 'UAH' %} </span><br>
                    {% endif %}
                </div>
            </div><hr class="hr">


    {% endfor %}
    </div>
    <div class="completed-buttons">
        <a  href="{% url 'product:shop' %}"><button class="comp-button" type="button">{% trans 'To shop' %}</button></a>
        <a  href="{% url 'order:completed_orders' %}"><button class="comp-button" type="button">{% trans 'All my orders' %}</button></a>
    </div>
</div>
{% endblock %}